SuncloakTown_PlayerHouse2_MapScripts::
	.byte 0


SuncloakTown_PlayerHouse2_Bed::
# 4 "data/maps/SuncloakTown_PlayerHouse2/scripts.pory"
	lock
# 5 "data/maps/SuncloakTown_PlayerHouse2/scripts.pory"
	msgbox SuncloakTown_PlayerHouse2_Bed_Text_0
# 6 "data/maps/SuncloakTown_PlayerHouse2/scripts.pory"
	release
	return


SuncloakTown_PlayerHouse2_Bed_Text_0:
# 5 "data/maps/SuncloakTown_PlayerHouse2/scripts.pory"
	.string "I should probably sleep in my own bed\n"
	.string "downstairs...$"
