gText_Birch_Welcome::
	.string "Hi! Sorry to keep you waiting!\p"
	.string "Welcome to the world of POKéMON!\p"
	.string "My name is BIRCH.\p"
	.string "But everyone calls me the POKéMON\n"
	.string "PROFESSOR.\p"
	.string "$"

gText_Coal_Welcome::
	.string "Hello and good afternoon everyone!\p"
	.string "My name is Professor Coal and ...\p"
	.string "... sorry, one moment please.\p"
	.string "$"

gText_Coal_UseFlash::
	.string "Pikachu! Use Flash!\p"
	.string "$"

gText_Coal_Sorry::
	.string "Sorry about that!\p"
	.string "When you've been delving as long\n"
	.string "as I have, you get quite used to\l"
	.string "the dark.\p"
	.string "$"

gText_Coal_MainSpeech::
	.string "Anyway, congratulations on your\n"
	.string "acceptance to the prestigious\l"
	.string "Hoenn Research Institute!\p"
	.string "Today in your orientation you will\n"
	.string "learn how we do things around here!\p"
	.string "$"

gText_Birch_Pokemon::
	.string "This is what we call a “POKéMON.”\p"
	.string "\n"
	.string "$"

gText_Birch_MainSpeech::
	.string "This world is widely inhabited by\n"
	.string "creatures known as POKéMON.\p"
	.string "We humans live alongside POKéMON,\n"
	.string "at times as friendly playmates, and\l"
	.string "at times as cooperative workmates.\p"
	.string "And sometimes, we band together\n"
	.string "and battle others like us.\p"
	.string "But despite our closeness, we don't\n"
	.string "know everything about POKéMON.\p"
	.string "In fact, there are many, many\n"
	.string "secrets surrounding POKéMON.\p"
	.string "To unravel POKéMON mysteries,\n"
	.string "I've been undertaking research.\l"
	.string "That's what I do.\p"
	.string "$"

gText_Birch_AndYouAre::
	.string "But first, let's introduce ourselves.$"

gText_Birch_BoyOrGirl::
	.string "Are you a boy?\n"
	.string "Or are you a girl?$"

gText_Birch_WhatStarter::
	.string "And what POKéMON\n"
	.string "do you have with you?$"

gText_Birch_WhatsYourName::
	.string "And what's your name?$"

gText_Birch_SoItsPlayer::
	.string "Welcome {PLAYER}{KUN}!$"

gText_Birch_YourePlayer::
	.string "Ah, okay!\p"
	.string "You're {PLAYER}{KUN} who's moving to my\n"
	.string "hometown of LITTLEROOT.\l"
	.string "I get it now!\p"
	.string "$"

gText_Birch_AreYouReady::
	.string "Fantastic!\p"
	.string "Now that we all know each other,\n"
	.string "let's get started!\p"
	.string "$"
