gText_Coal_Welcome::
	.string "Hello and good afternoon everyone!\p"
	.string "My name is Professor Coal and ...\p"
	.string "... sorry, one moment please.\p"
	.string "$"

gText_Coal_Sorry::
	.string "Sorry about that!\p"
	.string "When you've been researching as long\n"
	.string "as I have, you get quite used to\l"
	.string "the dark.\p"
	.string "$"

gText_Coal_MainSpeech::
	.string "Anyway, congratulations on your\n"
	.string "acceptance to the prestigious\l"
	.string "Hoenn Research Institute!\p"
	.string "Today in your orientation you will\n"
	.string "learn how we do things around here!\p"
	.string "$"

gText_Coal_Introduce::
	.string "But first, let's introduce ourselves.$"

gText_Coal_WhatStarter::
	.string "And what POKéMON\n"
	.string "do you have with you?$"

gText_Coal_WhatsYourName::
	.string "And what's your name?$"

gText_Coal_WelcomePlayerName::
	.string "Welcome {PLAYER}!\n"
    .string "Did I say that right?$"

gText_Coal_LetsGetStarted::
	.string "Fantastic!\p"
	.string "Now that we all know each other,\n"
	.string "let's get started!\p"
	.string "$"
